name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout code
      uses: actions/checkout@v4


    - name: Log inti the Docker Hub
      uses: docker/login-actions@v3
      with:
        username: ${{ secrets.DOCKER_randheeer }}
        password: ${{ secrets.DOCKER Randheer#123 }}


    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_randheeer }}/devops-project1:latest .


    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_randheeer }}/devops-project1:latest



